Gerenciamento_aniversario_ASPNET/Models/Pessoa.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Gerenciamento_aniversario_ASPNET.Models
{
    public class Pessoa
    {
        [Key]
        public int Id { get; set; }
        public string Nome { get; set; }
        public string SobreNome { get; set; }
        public DateTime DataDeAniversario { get; set; }
        public int DiasRestantes { get; set; }
        public int ProximoAniversario()
        {
            DateTime momento = DateTime.Today;
            DateTime dataAniversario = new DateTime(momento.Year, DataDeAniversario.Month, DataDeAniversario.Day);

            if (dataAniversario < momento)
            {
                dataAniversario = dataAniversario.AddYears(1);
            }

            int diferancaData = (dataAniversario - momento).Days;
            return diferancaData;
        }
    }
}

Gerenciamento_aniversario_ASPNET/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Gerenciamento_aniversario_ASPNET.Models;

namespace Gerenciamento_aniversario_ASPNET.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        
    }
}

Gerenciamento_aniversario_ASPNET/Controllers/PessoaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Gerenciamento_aniversario_ASPNET.Models;
using Gerenciamento_aniversario_ASPNET.Repository;


namespace Gerenciamento_aniversario_ASPNET.Controllers
{
    public class PessoaController : Controller
    {
        private PessoaRepository PessoaRepository { get; set; }

        public PessoaController(PessoaRepository pessoaRepository)
        {
            this.PessoaRepository = pessoaRepository;
        }

        // GET: Pessoa
        [Route("Pessoa/HappyBirthday")]
        public ActionResult HappyBirthday()
        {
            DateTime dataDeHoje = DateTime.Today;
            var pessoa = PessoaRepository.GetAll().Where(pessoa => pessoa.DataDeAniversario.Day.Equals(dataDeHoje.Day) && pessoa.DataDeAniversario.Month.Equals(dataDeHoje.Month));

            return View(pessoa);
        }

        // GET: Pessoa
        [Route("Pessoa/")]
        public ActionResult Index()
        {
            var pessoa = PessoaRepository.ListaOrdenada();
            return View(pessoa);
        }

        // GET: Pessoa/Details/5
        [Route("Pessoas/Details/{id}")]
        public ActionResult Details(int id)
        {
            var pessoa = this.PessoaRepository.GetById(id);
            return View(pessoa);
        }

        //GET: Pessoa/Buscar
        [Route("Pessoas/Search")]
        public ActionResult Search(string nome)
        {
            var pessoa = PessoaRepository.BuscarPorNome(nome);
            return View(pessoa);
        }

        // GET: Pessoa/Create
        [Route("Pessoas/Create")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Pessoa/Create
        [Route("Pessoas/Create")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Pessoa pessoa)
        {
            try
            {
                if (ModelState.IsValid == false)
                    return View();

                pessoa.DiasRestantes = pessoa.ProximoAniversario();
                PessoaRepository.Save(pessoa);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pessoa/Edit/5
        [Route("Pessoas/Edit/{id}")]
        public ActionResult Edit(int id)
        {
            var pessoa = this.PessoaRepository.GetById(id);

            return View(pessoa);
        }

        // POST: Pessoa/Edit/5
        [Route("Pessoas/Edit/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Pessoa pessoa)
        {
            try
            {
                if (ModelState.IsValid == false)
                    return View();

                var pessoaEdit = PessoaRepository.GetById(id);

                pessoaEdit.Nome = pessoa.Nome;
                pessoaEdit.SobreNome = pessoa.SobreNome;
                pessoaEdit.DataDeAniversario = pessoa.DataDeAniversario;

                PessoaRepository.Update(pessoaEdit);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Pessoa/Delete/5
        [Route("Pessoas/Delete/{id}")]
        public ActionResult Delete(int id)
        {
            var pessoa = this.PessoaRepository.GetById(id);
            return View(pessoa);
        }

        // POST: Pessoa/Delete/5
        [Route("Pessoas/Delete/{id}")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(Pessoa pessoa)
        {
            try
            {
                if (ModelState.IsValid == false)
                    return View();

                PessoaRepository.Delete(pessoa);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Gerenciamento_aniversario_ASPNET/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Gerenciamento_aniversario_ASPNET/Views/Pessoa/Create.cshtml
@model Gerenciamento_aniversario_ASPNET.Models.Pessoa

<h1>Create</h1>

<h4>Adicione uma nova pessoa pra ser lembrada (ou não)</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SobreNome" class="control-label"></label>
                <input asp-for="SobreNome" class="form-control" />
                <span asp-validation-for="SobreNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeAniversario" class="control-label"></label>
                <input asp-for="DataDeAniversario" class="form-control" />
                <span asp-validation-for="DataDeAniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gerenciamento_aniversario_ASPNET/Views/Pessoa/Delete.cshtml
@model Gerenciamento_aniversario_ASPNET.Models.Pessoa

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PessoaModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SobreNome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SobreNome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeAniversario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeAniversario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiasRestantes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiasRestantes)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para página principal</a>
    </form>
</div>

Gerenciamento_aniversario_ASPNET/Views/Pessoa/Details.cshtml
@model Gerenciamento_aniversario_ASPNET.Models.Pessoa

@{
    ViewData["Title"] = "Details";

}

<h1>Details</h1>

<div>
    <h4>PessoaModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SobreNome)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SobreNome)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DataDeAniversario)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DataDeAniversario)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DiasRestantes)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DiasRestantes)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Back to List</a>
</div>

Gerenciamento_aniversario_ASPNET/Views/Pessoa/Edit.cshtml
@model Gerenciamento_aniversario_ASPNET.Models.Pessoa

@{
    ViewData["Title"] = "Details";
}

<h1>Edit</h1>

<h4>PessoaModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" readonly />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SobreNome" class="control-label"></label>
                <input asp-for="SobreNome" class="form-control" />
                <span asp-validation-for="SobreNome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataDeAniversario" class="control-label"></label>
                <input asp-for="DataDeAniversario" class="form-control" />
                <span asp-validation-for="DataDeAniversario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para página principal</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Gerenciamento_aniversario_ASPNET/Views/Pessoa/HappyBirthday.cshtml
@model IEnumerable<Gerenciamento_aniversario_ASPNET.Models.Pessoa>

@{
    ViewData["Title"] = "HappyBirthday";
}

<h1>Happy Birthday!</h1>

<p>
    <a asp-action="Create">Create New</a> |
    <a asp-action="Index">Voltar para página principal</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SobreNome)
            </th>
            <th>
                Data de Aniversário
            </th>
            <th>
                Contagem Regressiva =D
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SobreNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataDeAniversario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiasRestantes)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

Gerenciamento_aniversario_ASPNET/Views/Pessoa/Index.cshtml
@model IEnumerable<Gerenciamento_aniversario_ASPNET.Models.Pessoa>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a> |
    <a asp-action="HappyBirthday">People you should buy stuff...now...quickly</a>
</p>
<form asp-action="Search">
    <div class="form-group">
        <input type="text" name="nome" placeholder="Insira o nome desejado..." class="form-control" required />
        <input type="submit" value="Search" class="btn btn-outline-primary" />
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SobreNome)
            </th>
            <th>
                Data de Aniversário
            </th>
            <th>
                Contagem Regressiva =D
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SobreNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataDeAniversario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiasRestantes)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

Gerenciamento_aniversario_ASPNET/Views/Pessoa/Search.cshtml
@model IEnumerable<Gerenciamento_aniversario_ASPNET.Models.Pessoa>

@{
    ViewData["Title"] = "Search";
}

<h1>Search</h1>

<p>
    <a asp-action="Index">Voltar para página principal</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SobreNome)
            </th>
            <th>
                Data de Aniversário
            </th>
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SobreNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataDeAniversario)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
        }
    </tbody>
</table>

Gerenciamento_aniversario_ASPNET/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Gerenciamento_aniversario_ASPNET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gerenciamento_aniversario_ASPNET</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pessoa" asp-action="Index">Gerenciamento de Pessoa</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Gerenciamento_aniversario_ASPNET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>